### ISSUE TITLE
Patch to add longoutput and performance data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [calestyo/check_yum#13]
```
See attached patch.


    Added perfdata and longoutput with ERRATA IDs
    
    Option added:
      -l - runs yum list-security to get advisories and packages
    Perfdata now shows how many updates are available.

```

Original issue reported on code.google.com by `tomas.ed...@gmail.com` on 13 Dec 2012 at 10:21

Attachments:
* [check_yum.patch](https://storage.googleapis.com/google-code-attachments/check-yum/issue-13/comment-0/check_yum.patch)

**Comment by calestyo** [comment]
No more reaction on this, thus closing for now.

Further, this issue is partially a duplicate of #18 (see also there for the same question about "total number of upgrades & number of security upgrades" vs. "number of non-security upgrades & number of security upgrades".

And I think the idea with printing the errata IDs has the same buffer length problems as described in issue #5, so your patch would need to solve it some way (e.g. as I've described it there).
