### ISSUE TITLE
Yum output not handled correctly

### ISSUE THREAD

**Issue by tinuzz** [calestyo/check_yum#19]
On RHEL 6, I get a lot of

  An update notice is broken, or duplicate, skipping: RHSA-2013:0188
  An update notice is broken, or duplicate, skipping: RHSA-2013:0215
  ...

recently. This triggers the warning in line 304-305 and the check doesn't report anything useful.

**Comment by calestyo** [comment]
I've seen tat before on a few systems, but then it always turned out to be either broken repositories or cache data, little one could properly do against from the check_yum side.

Also, I'm basically in maintenance mode only, right now, i.e. not actively developing check_yum but rather waiting for patches or someone capable to take over.

**Comment by calestyo** [comment]
If you still suffer form that, please reopen. Otherwise I'd close it now.
