### ISSUE TITLE
check_yum fills /var/tmp

### ISSUE THREAD

**Issue by bliles** [calestyo/check_yum#21]
Since check_yum generally runs as a non-privileged user, it caches rpm data to /var/tmp. On a machine with limited space, this can cause problems.

This page recommends forcing to /tmp for the tmp dir and also cleaning up the temporary files:
http://unix.stackexchange.com/questions/92257/yum-user-temp-files-var-tmp-yum-fills-up-with-repo-data

**Comment by calestyo** [comment]
Hey.

I assume you refer to when check_yum is invoked **without** "-C" respectively "--cache-only" which makes yum update it's repo data cache…

Well I don't think there's much of a proper solution to this one could do from the check_yum side.

- Either we'd clean the cache right after running (which would make it pointless) or provide some cron script which would do this every now and then. But in any case, we'd need to fiddle with the cache that is used by other yum programs, respectively yum itself… and I don't want to do that.

- Using /tmp, doesn't really change the above. We'd either need to clean it straight after running, or provide some cron job or similar. And there is no guarantee that /tmp is actually cleaned at reboot nor that the system is often rebooted. Plus we'd even set up one further yum repo cache location. Seems like a bad idea.

IMHO, the real "bug" here is in yum itself, in that it seems to not clean up stale repo cache files from repos no longer configured, when an update is done.
Of course I could just call "yum clean all" before calling yum without "-C", but again, I feel check_yum shouldn't do that, because it's task is not repo cache data management.


I personally, have a cron script on all remaining non-Debian nodes, which regularly clears and updates yum's repo data about like this:
```
output="$( yum --quiet --setopt='exit_on_lock=true' clean all 2>&1 )"
if [ $? -ne 0  -o  -n "${output}" ]; then #error handling
        printf 'Warning: Could not clean package repository data.\n' >&2
fi


output="$( yum --quiet --setopt='exit_on_lock=true' makecache 2>&1 )"
if [ $? -ne 0  -o  -n "${output}" ]; then #error handling
        printf 'Error: Could not update package repository data.\n' >&2
        exit 1
fi
exit 0
```
… and check_yum is invoked with -C.

In an ideal world, we'd have "-C" per default in check_yum, but I guess there would be many people which would then end up in not having their repos updated anymore because they don't do it on their own.

So I close this for now, until some more ideas/suggestions/etc. are provided.
